# Generated by Django 5.1.4 on 2025-03-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampoAmplio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Campo Amplio',
                'verbose_name_plural': 'Campos Amplios',
            },
        ),
    ]
