# Generated by Django 5.1.4 on 2025-03-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campoamplio',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=300, null=True, unique=True),
        ),
    ]
