# Generated by Django 5.1.4 on 2025-03-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0005_nivelacademico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoDetalladoPregrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Campo Detallado',
                'verbose_name_plural': 'Campos Detallados',
            },
        ),
    ]
