# Generated by Django 5.1.4 on 2025-03-18 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0007_campoamplioposgrado_campodetalladoposgrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_amplio_posgrado', models.ManyToManyField(blank=True, to='vacante.campoamplioposgrado')),
                ('campo_amplio_pregrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacante.campoampliopregrado')),
                ('campo_detallado_posgrado', models.ManyToManyField(blank=True, to='vacante.campodetalladoposgrado')),
                ('campo_detallado_pregrado', models.ManyToManyField(blank=True, to='vacante.campodetalladopregrado')),
                ('campo_especifico_posgrado', models.ManyToManyField(blank=True, to='vacante.campoespecificoposgrado')),
                ('campo_especifico_pregrado', models.ManyToManyField(blank=True, to='vacante.campoespecificopregrado')),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='vacante.nivelacademico')),
                ('posgrado', models.ManyToManyField(blank=True, to='vacante.nivelacademico')),
            ],
        ),
    ]
