# Generated by Django 5.1.4 on 2025-03-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0009_rename_nivel_educativo_vacante_nivel_academico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='campo_amplio_posgrado',
            field=models.ManyToManyField(blank=True, to='vacante.campoamplioposgrado'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='campo_amplio_pregrado',
            field=models.ManyToManyField(blank=True, to='vacante.campoampliopregrado'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='campo_detallado_posgrado',
            field=models.ManyToManyField(blank=True, to='vacante.campodetalladoposgrado'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='campo_detallado_pregrado',
            field=models.ManyToManyField(blank=True, to='vacante.campodetalladopregrado'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='campo_especifico_posgrado',
            field=models.ManyToManyField(blank=True, to='vacante.campoespecificoposgrado'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='campo_especifico_pregrado',
            field=models.ManyToManyField(blank=True, to='vacante.campoespecificopregrado'),
        ),
        migrations.DeleteModel(
            name='VacanteCampo',
        ),
    ]
