# Generated by Django 5.1.4 on 2025-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0011_remove_vacante_campo_amplio_posgrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vacante', models.IntegerField()),
                ('identificacion', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('es_interno', models.BooleanField()),
                ('titulo', models.CharField(max_length=255)),
                ('otro_titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_estudios', models.CharField(max_length=50)),
                ('fecha_fin_estudios', models.DateField()),
                ('fecha_diploma', models.DateField()),
                ('cumple_requisitos', models.BooleanField(default=False)),
                ('justificacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
