# Generated by Django 5.1.4 on 2025-03-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0012_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fecha_diploma',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fecha_fin_estudios',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
