# Generated by Django 5.1.4 on 2025-03-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0013_alter_candidato_fecha_diploma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración predeterminada', max_length=255)),
                ('col_id_vacante', models.IntegerField(default=0)),
                ('col_identificacion', models.IntegerField(default=1)),
                ('col_nombre', models.IntegerField(default=2)),
                ('col_es_interno', models.IntegerField(default=3)),
                ('col_titulo', models.IntegerField(default=4)),
                ('col_otro_titulo', models.IntegerField(default=5)),
                ('col_nivel_estudios', models.IntegerField(default=6)),
                ('col_fecha_fin_estudios', models.IntegerField(default=7)),
                ('col_fecha_diploma', models.IntegerField(default=8)),
            ],
        ),
    ]
