# Generated by Django 5.1.4 on 2025-03-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0014_configuracioncandidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_programa', models.CharField(max_length=500)),
                ('titulo_otorgado', models.CharField(max_length=500)),
                ('cine_f_2013_ac_campo_amplio', models.CharField(max_length=500)),
                ('cine_f_2013_ac_campo_especifico', models.CharField(max_length=500)),
                ('cine_f_2013_ac_campo_detallado', models.CharField(max_length=500)),
                ('area_de_conocimiento', models.CharField(max_length=255)),
                ('nucleo_basico_del_conocimiento', models.CharField(max_length=255)),
                ('nivel_academico', models.CharField(max_length=255)),
                ('nivel_de_formacion', models.CharField(max_length=255)),
            ],
        ),
    ]
