# Generated by Django 5.1.4 on 2025-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0015_programaacademico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaacademico',
            name='area_de_conocimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='cine_f_2013_ac_campo_amplio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='cine_f_2013_ac_campo_detallado',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='cine_f_2013_ac_campo_especifico',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='nivel_academico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='nivel_de_formacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='nombre_del_programa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='nucleo_basico_del_conocimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='titulo_otorgado',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
