# Generated by Django 5.1.4 on 2025-03-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0016_alter_programaacademico_area_de_conocimiento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramaAcademico',
            new_name='ProgramaAcademicoSnies',
        ),
    ]
