# Generated by Django 5.1.4 on 2025-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0017_rename_programaacademico_programaacademicosnies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cumple_requisitos',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
