# Generated by Django 5.1.4 on 2025-03-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0018_alter_candidato_cumple_requisitos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalenciaTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('otro_titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_estudios', models.CharField(max_length=255)),
                ('equivalente_snies', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
