# Generated by Django 5.1.4 on 2025-03-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0019_equivalenciatitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalenciatitulo',
            name='equivalente_snies',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equivalenciatitulo',
            name='nivel_estudios',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equivalenciatitulo',
            name='otro_titulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equivalenciatitulo',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
