# Generated by Django 5.1.4 on 2025-03-25 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0020_alter_equivalenciatitulo_equivalente_snies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadEquivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('revisado', models.BooleanField(default=False)),
                ('equivalencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='vacante.equivalenciatitulo')),
                ('sugerencia_snies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_asignadas', to='vacante.programaacademicosnies')),
            ],
        ),
    ]
