# Generated by Django 5.1.4 on 2025-03-26 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0020_alter_equivalenciatitulo_equivalente_snies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadEquivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('identificacion_candidato', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('otro_titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('revisado', models.BooleanField(default=False)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacante.candidato')),
            ],
        ),
    ]
