# Generated by Django 5.1.4 on 2025-03-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0021_novedadequivalencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalenciatitulo',
            name='id_candidato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equivalenciatitulo',
            name='id_vacante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equivalenciatitulo',
            name='nivel_estudios',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
