# Generated by Django 5.1.4 on 2025-03-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0022_equivalenciatitulo_id_candidato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedadequivalencia',
            name='candidato',
        ),
        migrations.AddField(
            model_name='novedadequivalencia',
            name='id_vacante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
