# Generated by Django 5.1.4 on 2025-03-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0023_remove_novedadequivalencia_candidato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedadequivalencia',
            name='revisado',
        ),
    ]
