# Generated by Django 5.1.4 on 2025-03-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0024_remove_novedadequivalencia_revisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadequivalencia',
            name='id_equivalencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
