# Generated by Django 5.1.4 on 2025-03-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0025_novedadequivalencia_id_equivalencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novedadequivalencia',
            old_name='id_equivalencia',
            new_name='equivalencia_snies',
        ),
        migrations.RemoveField(
            model_name='equivalenciatitulo',
            name='otro_titulo',
        ),
        migrations.RemoveField(
            model_name='novedadequivalencia',
            name='otro_titulo',
        ),
    ]
