# Generated by Django 5.1.4 on 2025-03-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0026_rename_id_equivalencia_novedadequivalencia_equivalencia_snies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalenciatitulo',
            name='otro_titulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
