# Generated by Django 5.1.4 on 2025-03-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0028_remove_equivalenciatitulo_otro_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadequivalencia',
            name='nivel_estudios',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='novedadequivalencia',
            name='equivalencia_snies',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
