# Generated by Django 5.1.4 on 2025-03-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0029_novedadequivalencia_nivel_estudios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadequivalencia',
            name='id_equivalencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
