# Generated by Django 5.1.4 on 2025-03-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0030_novedadequivalencia_id_equivalencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalenciatitulo',
            name='id_equivalencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
